name: doublestripe
favicon: null
layout_spectrum: 1
typography_spectrum: 0.5394265
title: 'DoubleStripe '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#171516'
    - '#FCD307'
    - '#E02878'
    - '#B4B3B4'
  brandStrength: 1
  lightness: 0.25
  saturation: 0
  rhythmicContrast: 0.5322581
purpose: []
